# Generated by Django 5.2.5 on 2025-08-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('scryfall_id', models.CharField(max_length=36, unique=True)),
                ('rating', models.FloatField(default=1500.0)),
                ('rating_deviation', models.FloatField(default=350.0)),
                ('volatility', models.FloatField(default=0.06)),
                ('image_uris', models.JSONField(default=dict)),
                ('card_faces', models.JSONField(default=list)),
                ('layout', models.CharField(default='normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
