# Generated by Django 5.2.5 on 2025-08-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='cmc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='color_identity',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='color_sort_key',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='image_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='num_colors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='oracle_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='toughness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CandidateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='KernelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.kernel')),
            ],
            options={
                'unique_together': {('kernel', 'card')},
            },
        ),
    ]
